"""Type stubs for the _alignx C++ extension module."""

from __future__ import annotations

from typing import Iterator, Optional

import numpy as np
import numpy.typing as npt

# ── Module attributes ────────────────────────────────────────────────────────

__version__: str
has_htslib: bool
has_zstd: bool
has_avx2: bool

# ── Enums ────────────────────────────────────────────────────────────────────

class ColumnId:
    qname: ColumnId
    flag: ColumnId
    pos: ColumnId
    mapq: ColumnId
    cigar: ColumnId
    mate_reference: ColumnId
    mate_pos: ColumnId
    template_length: ColumnId
    sequence: ColumnId
    quality: ColumnId
    tags: ColumnId

class CodecId:
    raw: CodecId
    pos_delta_varint: CodecId
    flag_bitpack: CodecId
    mapq_rle: CodecId
    seq_2bit_literal: CodecId
    cigar_token: CodecId
    qual_rle: CodecId
    qual_pack: CodecId
    qual_pack_compressed: CodecId
    qname_dict: CodecId
    tags_per_stream: CodecId
    cigar_dict: CodecId
    compressed: CodecId
    seq_ref_delta: CodecId

class Compression:
    none: Compression
    zstd: Compression

class QualityLossy:
    none: QualityLossy
    illumina8: QualityLossy

# ── Read-only data classes ───────────────────────────────────────────────────

class Record:
    @property
    def qname(self) -> str: ...
    @property
    def flag(self) -> int: ...
    @property
    def pos(self) -> int: ...
    @property
    def mapq(self) -> int: ...
    @property
    def cigar(self) -> str: ...
    @property
    def mate_reference(self) -> str: ...
    @property
    def mate_pos(self) -> int: ...
    @property
    def template_length(self) -> int: ...
    @property
    def sequence(self) -> str: ...
    @property
    def quality(self) -> str: ...
    @property
    def tags(self) -> str: ...

class Reference:
    @property
    def name(self) -> str: ...
    @property
    def length(self) -> int: ...

class Chunk:
    @property
    def ref_id(self) -> int: ...
    @property
    def start_pos(self) -> int: ...
    @property
    def end_pos(self) -> int: ...
    @property
    def records(self) -> list[Record]: ...
    def column_array(self, column: str) -> npt.NDArray[np.int32] | npt.NDArray[np.uint16] | npt.NDArray[np.uint8]: ...

class ChunkIndex:
    @property
    def ref_id(self) -> int: ...
    @property
    def start_pos(self) -> int: ...
    @property
    def end_pos(self) -> int: ...
    @property
    def record_count(self) -> int: ...
    @property
    def chunk_offset(self) -> int: ...
    @property
    def chunk_length(self) -> int: ...
    def overlaps(self, start: int, end: int) -> bool: ...

class FileMetadata:
    @property
    def source_path(self) -> str: ...
    @property
    def conversion_region(self) -> str: ...
    @property
    def is_subset(self) -> bool: ...

class FileIndex:
    @property
    def metadata(self) -> FileMetadata: ...
    @property
    def references(self) -> list[Reference]: ...
    @property
    def chunks(self) -> list[ChunkIndex]: ...
    def query_chunks(self, ref_id: int, start: int, end: int) -> list[ChunkIndex]: ...

class ChunkReadProfile:
    @property
    def bytes_read(self) -> int: ...
    @property
    def total_payload_bytes(self) -> int: ...
    @property
    def selected_payload_bytes(self) -> int: ...
    @property
    def total_columns(self) -> int: ...
    @property
    def selected_columns(self) -> int: ...

class CoverageResult:
    @property
    def reference(self) -> str: ...
    @property
    def start(self) -> int: ...
    @property
    def end(self) -> int: ...
    @property
    def depth(self) -> npt.NDArray[np.uint32]: ...
    @property
    def records_counted(self) -> int: ...
    def __len__(self) -> int: ...
    def __buffer__(self, flags: int, /) -> memoryview: ...

# ── Mutable option classes ───────────────────────────────────────────────────

class WriteOptions:
    def __init__(self) -> None: ...
    quality_compression: Compression
    column_compression: Compression
    quality_lossy: QualityLossy
    reference_fasta: Optional[str]

class RecordFilter:
    def __init__(self) -> None: ...
    flag_exclude: int
    min_mapq: int
    def is_active(self) -> bool: ...

# ── Axf1FileReader ───────────────────────────────────────────────────────────

class Axf1FileReader:
    @property
    def index(self) -> FileIndex: ...
    def query_chunks(self, ref_id: int, start: int, end: int) -> list[ChunkIndex]: ...
    def read_chunk(self, chunk: ChunkIndex) -> Chunk: ...
    def read_chunk_columns(self, chunk: ChunkIndex, columns: list[ColumnId]) -> Chunk: ...

# ── Module-level functions ───────────────────────────────────────────────────

def open(path: str) -> Axf1FileReader: ...

def view(
    input: str,
    region: str,
    reference: Optional[str] = None,
    flag_exclude: int = 0,
    min_mapq: int = 0,
) -> str: ...

def coverage(
    input: str,
    region: str,
    flag_exclude: int = 0,
    min_mapq: int = 0,
) -> CoverageResult: ...

def convert(
    input: str,
    output: str,
    region: Optional[str] = None,
    compression: str = "none",
    quality_lossy: str = "none",
    reference: Optional[str] = None,
) -> None: ...

def export_bam(
    input: str,
    output: str,
    hts_threads: Optional[int] = None,
) -> None: ...

# ── HTSlib-gated classes ────────────────────────────────────────────────────

class BamRecord:
    @property
    def qname(self) -> str: ...
    @property
    def reference_name(self) -> str: ...
    @property
    def position(self) -> int: ...
    @property
    def end_position(self) -> int: ...
    @property
    def template_length(self) -> int: ...
    @property
    def flag(self) -> int: ...
    @property
    def mapq(self) -> int: ...
    def is_unmapped(self) -> bool: ...

class BamReference:
    @property
    def name(self) -> str: ...
    @property
    def length(self) -> int: ...

class BamReader:
    @staticmethod
    def open(path: str, hts_threads: Optional[int] = None) -> BamReader: ...
    def fetch(self, region: str) -> None: ...
    def next_record(self) -> Optional[BamRecord]: ...
    def references(self) -> list[BamReference]: ...
    def has_index(self) -> bool: ...
    def __iter__(self) -> Iterator[BamRecord]: ...
    def __next__(self) -> BamRecord: ...
    def __enter__(self) -> BamReader: ...
    def __exit__(self, exc_type: object, exc_val: object, exc_tb: object) -> None: ...

class FastaContig:
    @property
    def name(self) -> str: ...
    @property
    def length(self) -> int: ...

class FastaReader:
    @staticmethod
    def open(path: str) -> FastaReader: ...
    def contigs(self) -> list[FastaContig]: ...
    def fetch_sequence(self, contig: str, start: int, end: int) -> str: ...
    def fetch_contig(self, contig: str) -> str: ...
    def compute_contig_sha256(self, contig: str) -> bytes: ...
    def __enter__(self) -> FastaReader: ...
    def __exit__(self, exc_type: object, exc_val: object, exc_tb: object) -> None: ...
